// C++ by default does not allow a function with a template argument to take an initializer list
// Therefore, in order to address that, there needs to be a wrapper for the function
// This can be made below with macros
#include <vector>
#include "utils_macros.h"

#ifndef NT_REFLECTION_NAMED_ARGUMENTS_INITIALIZER_LIST_HPP__
#define NT_REFLECTION_NAMED_ARGUMENTS_INITIALIZER_LIST_HPP__

namespace nt::named_arguments::details{
template<typename T>
struct is_initializer_list : std::false_type {};

template<typename T>
struct is_initializer_list<std::initializer_list<T>> : std::true_type {};
}

#define NT_INITIALIZER_LIST_FORWARD(num) std::forward<std::conditional_t<::nt::named_arguments::details::is_initializer_list<std::decay_t<decltype(_##num)>>::value, std::initializer_list<T##num>, T##num> >(_##num)
#define NT_LARG(num) std::initializer_list<T##num>&& _##num
#define NT_TARG(num) T##num&& _##num


#define NT_NAMED_INITIALIZER_COMBO100(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO99(MCNAME, N, f1, f2, NT_LARG(99),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO99(MCNAME, N, f1, f2, NT_TARG(99), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO99(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO98(MCNAME, N, f1, f2, NT_LARG(98),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO98(MCNAME, N, f1, f2, NT_TARG(98), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO98(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO97(MCNAME, N, f1, f2, NT_LARG(97),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO97(MCNAME, N, f1, f2, NT_TARG(97), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO97(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO96(MCNAME, N, f1, f2, NT_LARG(96),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO96(MCNAME, N, f1, f2, NT_TARG(96), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO96(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO95(MCNAME, N, f1, f2, NT_LARG(95),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO95(MCNAME, N, f1, f2, NT_TARG(95), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO95(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO94(MCNAME, N, f1, f2, NT_LARG(94),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO94(MCNAME, N, f1, f2, NT_TARG(94), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO94(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO93(MCNAME, N, f1, f2, NT_LARG(93),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO93(MCNAME, N, f1, f2, NT_TARG(93), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO93(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO92(MCNAME, N, f1, f2, NT_LARG(92),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO92(MCNAME, N, f1, f2, NT_TARG(92), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO92(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO91(MCNAME, N, f1, f2, NT_LARG(91),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO91(MCNAME, N, f1, f2, NT_TARG(91), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO91(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO90(MCNAME, N, f1, f2, NT_LARG(90),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO90(MCNAME, N, f1, f2, NT_TARG(90), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO90(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO89(MCNAME, N, f1, f2, NT_LARG(89),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO89(MCNAME, N, f1, f2, NT_TARG(89), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO89(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO88(MCNAME, N, f1, f2, NT_LARG(88),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO88(MCNAME, N, f1, f2, NT_TARG(88), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO88(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO87(MCNAME, N, f1, f2, NT_LARG(87),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO87(MCNAME, N, f1, f2, NT_TARG(87), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO87(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO86(MCNAME, N, f1, f2, NT_LARG(86),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO86(MCNAME, N, f1, f2, NT_TARG(86), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO86(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO85(MCNAME, N, f1, f2, NT_LARG(85),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO85(MCNAME, N, f1, f2, NT_TARG(85), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO85(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO84(MCNAME, N, f1, f2, NT_LARG(84),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO84(MCNAME, N, f1, f2, NT_TARG(84), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO84(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO83(MCNAME, N, f1, f2, NT_LARG(83),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO83(MCNAME, N, f1, f2, NT_TARG(83), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO83(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO82(MCNAME, N, f1, f2, NT_LARG(82),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO82(MCNAME, N, f1, f2, NT_TARG(82), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO82(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO81(MCNAME, N, f1, f2, NT_LARG(81),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO81(MCNAME, N, f1, f2, NT_TARG(81), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO81(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO80(MCNAME, N, f1, f2, NT_LARG(80),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO80(MCNAME, N, f1, f2, NT_TARG(80), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO80(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO79(MCNAME, N, f1, f2, NT_LARG(79),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO79(MCNAME, N, f1, f2, NT_TARG(79), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO79(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO78(MCNAME, N, f1, f2, NT_LARG(78),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO78(MCNAME, N, f1, f2, NT_TARG(78), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO78(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO77(MCNAME, N, f1, f2, NT_LARG(77),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO77(MCNAME, N, f1, f2, NT_TARG(77), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO77(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO76(MCNAME, N, f1, f2, NT_LARG(76),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO76(MCNAME, N, f1, f2, NT_TARG(76), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO76(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO75(MCNAME, N, f1, f2, NT_LARG(75),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO75(MCNAME, N, f1, f2, NT_TARG(75), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO75(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO74(MCNAME, N, f1, f2, NT_LARG(74),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO74(MCNAME, N, f1, f2, NT_TARG(74), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO74(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO73(MCNAME, N, f1, f2, NT_LARG(73),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO73(MCNAME, N, f1, f2, NT_TARG(73), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO73(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO72(MCNAME, N, f1, f2, NT_LARG(72),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO72(MCNAME, N, f1, f2, NT_TARG(72), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO72(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO71(MCNAME, N, f1, f2, NT_LARG(71),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO71(MCNAME, N, f1, f2, NT_TARG(71), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO71(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO70(MCNAME, N, f1, f2, NT_LARG(70),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO70(MCNAME, N, f1, f2, NT_TARG(70), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO70(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO69(MCNAME, N, f1, f2, NT_LARG(69),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO69(MCNAME, N, f1, f2, NT_TARG(69), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO69(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO68(MCNAME, N, f1, f2, NT_LARG(68),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO68(MCNAME, N, f1, f2, NT_TARG(68), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO68(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO67(MCNAME, N, f1, f2, NT_LARG(67),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO67(MCNAME, N, f1, f2, NT_TARG(67), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO67(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO66(MCNAME, N, f1, f2, NT_LARG(66),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO66(MCNAME, N, f1, f2, NT_TARG(66), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO66(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO65(MCNAME, N, f1, f2, NT_LARG(65),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO65(MCNAME, N, f1, f2, NT_TARG(65), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO65(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO64(MCNAME, N, f1, f2, NT_LARG(64),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO64(MCNAME, N, f1, f2, NT_TARG(64), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO64(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO63(MCNAME, N, f1, f2, NT_LARG(63),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO63(MCNAME, N, f1, f2, NT_TARG(63), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO63(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO62(MCNAME, N, f1, f2, NT_LARG(62),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO62(MCNAME, N, f1, f2, NT_TARG(62), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO62(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO61(MCNAME, N, f1, f2, NT_LARG(61),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO61(MCNAME, N, f1, f2, NT_TARG(61), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO61(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO60(MCNAME, N, f1, f2, NT_LARG(60),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO60(MCNAME, N, f1, f2, NT_TARG(60), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO60(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO59(MCNAME, N, f1, f2, NT_LARG(59),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO59(MCNAME, N, f1, f2, NT_TARG(59), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO59(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO58(MCNAME, N, f1, f2, NT_LARG(58),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO58(MCNAME, N, f1, f2, NT_TARG(58), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO58(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO57(MCNAME, N, f1, f2, NT_LARG(57),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO57(MCNAME, N, f1, f2, NT_TARG(57), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO57(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO56(MCNAME, N, f1, f2, NT_LARG(56),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO56(MCNAME, N, f1, f2, NT_TARG(56), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO56(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO55(MCNAME, N, f1, f2, NT_LARG(55),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO55(MCNAME, N, f1, f2, NT_TARG(55), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO55(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO54(MCNAME, N, f1, f2, NT_LARG(54),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO54(MCNAME, N, f1, f2, NT_TARG(54), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO54(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO53(MCNAME, N, f1, f2, NT_LARG(53),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO53(MCNAME, N, f1, f2, NT_TARG(53), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO53(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO52(MCNAME, N, f1, f2, NT_LARG(52),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO52(MCNAME, N, f1, f2, NT_TARG(52), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO52(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO51(MCNAME, N, f1, f2, NT_LARG(51),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO51(MCNAME, N, f1, f2, NT_TARG(51), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO51(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO50(MCNAME, N, f1, f2, NT_LARG(50),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO50(MCNAME, N, f1, f2, NT_TARG(50), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO50(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO49(MCNAME, N, f1, f2, NT_LARG(49),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO49(MCNAME, N, f1, f2, NT_TARG(49), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO49(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO48(MCNAME, N, f1, f2, NT_LARG(48),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO48(MCNAME, N, f1, f2, NT_TARG(48), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO48(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO47(MCNAME, N, f1, f2, NT_LARG(47),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO47(MCNAME, N, f1, f2, NT_TARG(47), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO47(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO46(MCNAME, N, f1, f2, NT_LARG(46),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO46(MCNAME, N, f1, f2, NT_TARG(46), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO46(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO45(MCNAME, N, f1, f2, NT_LARG(45),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO45(MCNAME, N, f1, f2, NT_TARG(45), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO45(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO44(MCNAME, N, f1, f2, NT_LARG(44),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO44(MCNAME, N, f1, f2, NT_TARG(44), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO44(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO43(MCNAME, N, f1, f2, NT_LARG(43),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO43(MCNAME, N, f1, f2, NT_TARG(43), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO43(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO42(MCNAME, N, f1, f2, NT_LARG(42),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO42(MCNAME, N, f1, f2, NT_TARG(42), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO42(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO41(MCNAME, N, f1, f2, NT_LARG(41),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO41(MCNAME, N, f1, f2, NT_TARG(41), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO41(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO40(MCNAME, N, f1, f2, NT_LARG(40),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO40(MCNAME, N, f1, f2, NT_TARG(40), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO40(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO39(MCNAME, N, f1, f2, NT_LARG(39),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO39(MCNAME, N, f1, f2, NT_TARG(39), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO39(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO38(MCNAME, N, f1, f2, NT_LARG(38),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO38(MCNAME, N, f1, f2, NT_TARG(38), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO38(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO37(MCNAME, N, f1, f2, NT_LARG(37),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO37(MCNAME, N, f1, f2, NT_TARG(37), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO37(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO36(MCNAME, N, f1, f2, NT_LARG(36),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO36(MCNAME, N, f1, f2, NT_TARG(36), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO36(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO35(MCNAME, N, f1, f2, NT_LARG(35),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO35(MCNAME, N, f1, f2, NT_TARG(35), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO35(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO34(MCNAME, N, f1, f2, NT_LARG(34),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO34(MCNAME, N, f1, f2, NT_TARG(34), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO34(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO33(MCNAME, N, f1, f2, NT_LARG(33),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO33(MCNAME, N, f1, f2, NT_TARG(33), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO33(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO32(MCNAME, N, f1, f2, NT_LARG(32),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO32(MCNAME, N, f1, f2, NT_TARG(32), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO32(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO31(MCNAME, N, f1, f2, NT_LARG(31),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO31(MCNAME, N, f1, f2, NT_TARG(31), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO31(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO30(MCNAME, N, f1, f2, NT_LARG(30),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO30(MCNAME, N, f1, f2, NT_TARG(30), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO30(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO29(MCNAME, N, f1, f2, NT_LARG(29),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO29(MCNAME, N, f1, f2, NT_TARG(29), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO29(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO28(MCNAME, N, f1, f2, NT_LARG(28),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO28(MCNAME, N, f1, f2, NT_TARG(28), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO28(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO27(MCNAME, N, f1, f2, NT_LARG(27),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO27(MCNAME, N, f1, f2, NT_TARG(27), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO27(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO26(MCNAME, N, f1, f2, NT_LARG(26),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO26(MCNAME, N, f1, f2, NT_TARG(26), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO26(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO25(MCNAME, N, f1, f2, NT_LARG(25),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO25(MCNAME, N, f1, f2, NT_TARG(25), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO25(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO24(MCNAME, N, f1, f2, NT_LARG(24),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO24(MCNAME, N, f1, f2, NT_TARG(24), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO24(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO23(MCNAME, N, f1, f2, NT_LARG(23),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO23(MCNAME, N, f1, f2, NT_TARG(23), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO23(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO22(MCNAME, N, f1, f2, NT_LARG(22),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO22(MCNAME, N, f1, f2, NT_TARG(22), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO22(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO21(MCNAME, N, f1, f2, NT_LARG(21),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO21(MCNAME, N, f1, f2, NT_TARG(21), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO21(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO20(MCNAME, N, f1, f2, NT_LARG(20),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO20(MCNAME, N, f1, f2, NT_TARG(20), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO20(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO19(MCNAME, N, f1, f2, NT_LARG(19),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO19(MCNAME, N, f1, f2, NT_TARG(19), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO19(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO18(MCNAME, N, f1, f2, NT_LARG(18),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO18(MCNAME, N, f1, f2, NT_TARG(18), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO18(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO17(MCNAME, N, f1, f2, NT_LARG(17),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO17(MCNAME, N, f1, f2, NT_TARG(17), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO17(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO16(MCNAME, N, f1, f2, NT_LARG(16),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO16(MCNAME, N, f1, f2, NT_TARG(16), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO16(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO15(MCNAME, N, f1, f2, NT_LARG(15),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO15(MCNAME, N, f1, f2, NT_TARG(15), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO15(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO14(MCNAME, N, f1, f2, NT_LARG(14),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO14(MCNAME, N, f1, f2, NT_TARG(14), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO14(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO13(MCNAME, N, f1, f2, NT_LARG(13),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO13(MCNAME, N, f1, f2, NT_TARG(13), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO13(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO12(MCNAME, N, f1, f2, NT_LARG(12),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO12(MCNAME, N, f1, f2, NT_TARG(12), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO12(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO11(MCNAME, N, f1, f2, NT_LARG(11),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO11(MCNAME, N, f1, f2, NT_TARG(11), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO11(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO10(MCNAME, N, f1, f2, NT_LARG(10),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO10(MCNAME, N, f1, f2, NT_TARG(10), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO10(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO9(MCNAME, N, f1, f2, NT_LARG(9),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO9(MCNAME, N, f1, f2, NT_TARG(9), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO9(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO8(MCNAME, N, f1, f2, NT_LARG(8),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO8(MCNAME, N, f1, f2, NT_TARG(8), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO8(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO7(MCNAME, N, f1, f2, NT_LARG(7),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO7(MCNAME, N, f1, f2, NT_TARG(7), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO7(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO6(MCNAME, N, f1, f2, NT_LARG(6),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO6(MCNAME, N, f1, f2, NT_TARG(6), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO6(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO5(MCNAME, N, f1, f2, NT_LARG(5),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO5(MCNAME, N, f1, f2, NT_TARG(5), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO5(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO4(MCNAME, N, f1, f2, NT_LARG(4),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO4(MCNAME, N, f1, f2, NT_TARG(4), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO4(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO3(MCNAME, N, f1, f2, NT_LARG(3),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO3(MCNAME, N, f1, f2, NT_TARG(3), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO3(MCNAME, N, f1, f2, ...) NT_NAMED_INITIALIZER_COMBO2(MCNAME, N, f1, f2, NT_LARG(2),__VA_ARGS__)\
                                                            NT_NAMED_INITIALIZER_COMBO2(MCNAME, N, f1, f2, NT_TARG(2), __VA_ARGS__)
#define NT_NAMED_INITIALIZER_COMBO2(MCNAME, N, f1, f2, ...) MCNAME(N, f1, f2, (NT_LARG(1),__VA_ARGS__))\
                                                            MCNAME(N, f1, f2, (NT_TARG(1), __VA_ARGS__))
#define NT_NAMED_INITIALIZER_COMBO1(MCNAME, N, f1, f2, ...) MCNAME(N, f1, f2, (__VA_ARGS__))

#define NT_NAMED_INITIALIZER_TCOMBO1 typename T1
#define NT_NAMED_INITIALIZER_TCOMBO2 NT_NAMED_INITIALIZER_TCOMBO1, typename T2
#define NT_NAMED_INITIALIZER_TCOMBO3 NT_NAMED_INITIALIZER_TCOMBO2, typename T3
#define NT_NAMED_INITIALIZER_TCOMBO4 NT_NAMED_INITIALIZER_TCOMBO3, typename T4
#define NT_NAMED_INITIALIZER_TCOMBO5 NT_NAMED_INITIALIZER_TCOMBO4, typename T5
#define NT_NAMED_INITIALIZER_TCOMBO6 NT_NAMED_INITIALIZER_TCOMBO5, typename T6
#define NT_NAMED_INITIALIZER_TCOMBO7 NT_NAMED_INITIALIZER_TCOMBO6, typename T7
#define NT_NAMED_INITIALIZER_TCOMBO8 NT_NAMED_INITIALIZER_TCOMBO7, typename T8
#define NT_NAMED_INITIALIZER_TCOMBO9 NT_NAMED_INITIALIZER_TCOMBO8, typename T9
#define NT_NAMED_INITIALIZER_TCOMBO10 NT_NAMED_INITIALIZER_TCOMBO9, typename T10
#define NT_NAMED_INITIALIZER_TCOMBO11 NT_NAMED_INITIALIZER_TCOMBO10, typename T11
#define NT_NAMED_INITIALIZER_TCOMBO12 NT_NAMED_INITIALIZER_TCOMBO11, typename T12
#define NT_NAMED_INITIALIZER_TCOMBO13 NT_NAMED_INITIALIZER_TCOMBO12, typename T13
#define NT_NAMED_INITIALIZER_TCOMBO14 NT_NAMED_INITIALIZER_TCOMBO13, typename T14
#define NT_NAMED_INITIALIZER_TCOMBO15 NT_NAMED_INITIALIZER_TCOMBO14, typename T15
#define NT_NAMED_INITIALIZER_TCOMBO16 NT_NAMED_INITIALIZER_TCOMBO15, typename T16
#define NT_NAMED_INITIALIZER_TCOMBO17 NT_NAMED_INITIALIZER_TCOMBO16, typename T17
#define NT_NAMED_INITIALIZER_TCOMBO18 NT_NAMED_INITIALIZER_TCOMBO17, typename T18
#define NT_NAMED_INITIALIZER_TCOMBO19 NT_NAMED_INITIALIZER_TCOMBO18, typename T19
#define NT_NAMED_INITIALIZER_TCOMBO20 NT_NAMED_INITIALIZER_TCOMBO19, typename T20
#define NT_NAMED_INITIALIZER_TCOMBO21 NT_NAMED_INITIALIZER_TCOMBO20, typename T21
#define NT_NAMED_INITIALIZER_TCOMBO22 NT_NAMED_INITIALIZER_TCOMBO21, typename T22
#define NT_NAMED_INITIALIZER_TCOMBO23 NT_NAMED_INITIALIZER_TCOMBO22, typename T23
#define NT_NAMED_INITIALIZER_TCOMBO24 NT_NAMED_INITIALIZER_TCOMBO23, typename T24
#define NT_NAMED_INITIALIZER_TCOMBO25 NT_NAMED_INITIALIZER_TCOMBO24, typename T25
#define NT_NAMED_INITIALIZER_TCOMBO26 NT_NAMED_INITIALIZER_TCOMBO25, typename T26
#define NT_NAMED_INITIALIZER_TCOMBO27 NT_NAMED_INITIALIZER_TCOMBO26, typename T27
#define NT_NAMED_INITIALIZER_TCOMBO28 NT_NAMED_INITIALIZER_TCOMBO27, typename T28
#define NT_NAMED_INITIALIZER_TCOMBO29 NT_NAMED_INITIALIZER_TCOMBO28, typename T29
#define NT_NAMED_INITIALIZER_TCOMBO30 NT_NAMED_INITIALIZER_TCOMBO29, typename T30
#define NT_NAMED_INITIALIZER_TCOMBO31 NT_NAMED_INITIALIZER_TCOMBO30, typename T31
#define NT_NAMED_INITIALIZER_TCOMBO32 NT_NAMED_INITIALIZER_TCOMBO31, typename T32
#define NT_NAMED_INITIALIZER_TCOMBO33 NT_NAMED_INITIALIZER_TCOMBO32, typename T33
#define NT_NAMED_INITIALIZER_TCOMBO34 NT_NAMED_INITIALIZER_TCOMBO33, typename T34
#define NT_NAMED_INITIALIZER_TCOMBO35 NT_NAMED_INITIALIZER_TCOMBO34, typename T35
#define NT_NAMED_INITIALIZER_TCOMBO36 NT_NAMED_INITIALIZER_TCOMBO35, typename T36
#define NT_NAMED_INITIALIZER_TCOMBO37 NT_NAMED_INITIALIZER_TCOMBO36, typename T37
#define NT_NAMED_INITIALIZER_TCOMBO38 NT_NAMED_INITIALIZER_TCOMBO37, typename T38
#define NT_NAMED_INITIALIZER_TCOMBO39 NT_NAMED_INITIALIZER_TCOMBO38, typename T39
#define NT_NAMED_INITIALIZER_TCOMBO40 NT_NAMED_INITIALIZER_TCOMBO39, typename T40
#define NT_NAMED_INITIALIZER_TCOMBO41 NT_NAMED_INITIALIZER_TCOMBO40, typename T41
#define NT_NAMED_INITIALIZER_TCOMBO42 NT_NAMED_INITIALIZER_TCOMBO41, typename T42
#define NT_NAMED_INITIALIZER_TCOMBO43 NT_NAMED_INITIALIZER_TCOMBO42, typename T43
#define NT_NAMED_INITIALIZER_TCOMBO44 NT_NAMED_INITIALIZER_TCOMBO43, typename T44
#define NT_NAMED_INITIALIZER_TCOMBO45 NT_NAMED_INITIALIZER_TCOMBO44, typename T45
#define NT_NAMED_INITIALIZER_TCOMBO46 NT_NAMED_INITIALIZER_TCOMBO45, typename T46
#define NT_NAMED_INITIALIZER_TCOMBO47 NT_NAMED_INITIALIZER_TCOMBO46, typename T47
#define NT_NAMED_INITIALIZER_TCOMBO48 NT_NAMED_INITIALIZER_TCOMBO47, typename T48
#define NT_NAMED_INITIALIZER_TCOMBO49 NT_NAMED_INITIALIZER_TCOMBO48, typename T49
#define NT_NAMED_INITIALIZER_TCOMBO50 NT_NAMED_INITIALIZER_TCOMBO49, typename T50
#define NT_NAMED_INITIALIZER_TCOMBO51 NT_NAMED_INITIALIZER_TCOMBO50, typename T51
#define NT_NAMED_INITIALIZER_TCOMBO52 NT_NAMED_INITIALIZER_TCOMBO51, typename T52
#define NT_NAMED_INITIALIZER_TCOMBO53 NT_NAMED_INITIALIZER_TCOMBO52, typename T53
#define NT_NAMED_INITIALIZER_TCOMBO54 NT_NAMED_INITIALIZER_TCOMBO53, typename T54
#define NT_NAMED_INITIALIZER_TCOMBO55 NT_NAMED_INITIALIZER_TCOMBO54, typename T55
#define NT_NAMED_INITIALIZER_TCOMBO56 NT_NAMED_INITIALIZER_TCOMBO55, typename T56
#define NT_NAMED_INITIALIZER_TCOMBO57 NT_NAMED_INITIALIZER_TCOMBO56, typename T57
#define NT_NAMED_INITIALIZER_TCOMBO58 NT_NAMED_INITIALIZER_TCOMBO57, typename T58
#define NT_NAMED_INITIALIZER_TCOMBO59 NT_NAMED_INITIALIZER_TCOMBO58, typename T59
#define NT_NAMED_INITIALIZER_TCOMBO60 NT_NAMED_INITIALIZER_TCOMBO59, typename T60
#define NT_NAMED_INITIALIZER_TCOMBO61 NT_NAMED_INITIALIZER_TCOMBO60, typename T61
#define NT_NAMED_INITIALIZER_TCOMBO62 NT_NAMED_INITIALIZER_TCOMBO61, typename T62
#define NT_NAMED_INITIALIZER_TCOMBO63 NT_NAMED_INITIALIZER_TCOMBO62, typename T63
#define NT_NAMED_INITIALIZER_TCOMBO64 NT_NAMED_INITIALIZER_TCOMBO63, typename T64
#define NT_NAMED_INITIALIZER_TCOMBO65 NT_NAMED_INITIALIZER_TCOMBO64, typename T65
#define NT_NAMED_INITIALIZER_TCOMBO66 NT_NAMED_INITIALIZER_TCOMBO65, typename T66
#define NT_NAMED_INITIALIZER_TCOMBO67 NT_NAMED_INITIALIZER_TCOMBO66, typename T67
#define NT_NAMED_INITIALIZER_TCOMBO68 NT_NAMED_INITIALIZER_TCOMBO67, typename T68
#define NT_NAMED_INITIALIZER_TCOMBO69 NT_NAMED_INITIALIZER_TCOMBO68, typename T69
#define NT_NAMED_INITIALIZER_TCOMBO70 NT_NAMED_INITIALIZER_TCOMBO69, typename T70
#define NT_NAMED_INITIALIZER_TCOMBO71 NT_NAMED_INITIALIZER_TCOMBO70, typename T71
#define NT_NAMED_INITIALIZER_TCOMBO72 NT_NAMED_INITIALIZER_TCOMBO71, typename T72
#define NT_NAMED_INITIALIZER_TCOMBO73 NT_NAMED_INITIALIZER_TCOMBO72, typename T73
#define NT_NAMED_INITIALIZER_TCOMBO74 NT_NAMED_INITIALIZER_TCOMBO73, typename T74
#define NT_NAMED_INITIALIZER_TCOMBO75 NT_NAMED_INITIALIZER_TCOMBO74, typename T75
#define NT_NAMED_INITIALIZER_TCOMBO76 NT_NAMED_INITIALIZER_TCOMBO75, typename T76
#define NT_NAMED_INITIALIZER_TCOMBO77 NT_NAMED_INITIALIZER_TCOMBO76, typename T77
#define NT_NAMED_INITIALIZER_TCOMBO78 NT_NAMED_INITIALIZER_TCOMBO77, typename T78
#define NT_NAMED_INITIALIZER_TCOMBO79 NT_NAMED_INITIALIZER_TCOMBO78, typename T79
#define NT_NAMED_INITIALIZER_TCOMBO80 NT_NAMED_INITIALIZER_TCOMBO79, typename T80
#define NT_NAMED_INITIALIZER_TCOMBO81 NT_NAMED_INITIALIZER_TCOMBO80, typename T81
#define NT_NAMED_INITIALIZER_TCOMBO82 NT_NAMED_INITIALIZER_TCOMBO81, typename T82
#define NT_NAMED_INITIALIZER_TCOMBO83 NT_NAMED_INITIALIZER_TCOMBO82, typename T83
#define NT_NAMED_INITIALIZER_TCOMBO84 NT_NAMED_INITIALIZER_TCOMBO83, typename T84
#define NT_NAMED_INITIALIZER_TCOMBO85 NT_NAMED_INITIALIZER_TCOMBO84, typename T85
#define NT_NAMED_INITIALIZER_TCOMBO86 NT_NAMED_INITIALIZER_TCOMBO85, typename T86
#define NT_NAMED_INITIALIZER_TCOMBO87 NT_NAMED_INITIALIZER_TCOMBO86, typename T87
#define NT_NAMED_INITIALIZER_TCOMBO88 NT_NAMED_INITIALIZER_TCOMBO87, typename T88
#define NT_NAMED_INITIALIZER_TCOMBO89 NT_NAMED_INITIALIZER_TCOMBO88, typename T89
#define NT_NAMED_INITIALIZER_TCOMBO90 NT_NAMED_INITIALIZER_TCOMBO89, typename T90
#define NT_NAMED_INITIALIZER_TCOMBO91 NT_NAMED_INITIALIZER_TCOMBO90, typename T91
#define NT_NAMED_INITIALIZER_TCOMBO92 NT_NAMED_INITIALIZER_TCOMBO91, typename T92
#define NT_NAMED_INITIALIZER_TCOMBO93 NT_NAMED_INITIALIZER_TCOMBO92, typename T93
#define NT_NAMED_INITIALIZER_TCOMBO94 NT_NAMED_INITIALIZER_TCOMBO93, typename T94
#define NT_NAMED_INITIALIZER_TCOMBO95 NT_NAMED_INITIALIZER_TCOMBO94, typename T95
#define NT_NAMED_INITIALIZER_TCOMBO96 NT_NAMED_INITIALIZER_TCOMBO95, typename T96
#define NT_NAMED_INITIALIZER_TCOMBO97 NT_NAMED_INITIALIZER_TCOMBO96, typename T97
#define NT_NAMED_INITIALIZER_TCOMBO98 NT_NAMED_INITIALIZER_TCOMBO97, typename T98
#define NT_NAMED_INITIALIZER_TCOMBO99 NT_NAMED_INITIALIZER_TCOMBO98, typename T99
#define NT_NAMED_INITIALIZER_TCOMBO100 NT_NAMED_INITIALIZER_TCOMBO99, typename T100

#define NT_NAMED_INITIALIZER_NCOMBO1 NT_INITIALIZER_LIST_FORWARD(1)
#define NT_NAMED_INITIALIZER_NCOMBO2 NT_NAMED_INITIALIZER_NCOMBO1, NT_INITIALIZER_LIST_FORWARD(2)
#define NT_NAMED_INITIALIZER_NCOMBO3 NT_NAMED_INITIALIZER_NCOMBO2, NT_INITIALIZER_LIST_FORWARD(3)
#define NT_NAMED_INITIALIZER_NCOMBO4 NT_NAMED_INITIALIZER_NCOMBO3, NT_INITIALIZER_LIST_FORWARD(4)
#define NT_NAMED_INITIALIZER_NCOMBO5 NT_NAMED_INITIALIZER_NCOMBO4, NT_INITIALIZER_LIST_FORWARD(5)
#define NT_NAMED_INITIALIZER_NCOMBO6 NT_NAMED_INITIALIZER_NCOMBO5, NT_INITIALIZER_LIST_FORWARD(6)
#define NT_NAMED_INITIALIZER_NCOMBO7 NT_NAMED_INITIALIZER_NCOMBO6, NT_INITIALIZER_LIST_FORWARD(7)
#define NT_NAMED_INITIALIZER_NCOMBO8 NT_NAMED_INITIALIZER_NCOMBO7, NT_INITIALIZER_LIST_FORWARD(8)
#define NT_NAMED_INITIALIZER_NCOMBO9 NT_NAMED_INITIALIZER_NCOMBO8, NT_INITIALIZER_LIST_FORWARD(9)
#define NT_NAMED_INITIALIZER_NCOMBO10 NT_NAMED_INITIALIZER_NCOMBO9, NT_INITIALIZER_LIST_FORWARD(10)
#define NT_NAMED_INITIALIZER_NCOMBO11 NT_NAMED_INITIALIZER_NCOMBO10, NT_INITIALIZER_LIST_FORWARD(11)
#define NT_NAMED_INITIALIZER_NCOMBO12 NT_NAMED_INITIALIZER_NCOMBO11, NT_INITIALIZER_LIST_FORWARD(12)
#define NT_NAMED_INITIALIZER_NCOMBO13 NT_NAMED_INITIALIZER_NCOMBO12, NT_INITIALIZER_LIST_FORWARD(13)
#define NT_NAMED_INITIALIZER_NCOMBO14 NT_NAMED_INITIALIZER_NCOMBO13, NT_INITIALIZER_LIST_FORWARD(14)
#define NT_NAMED_INITIALIZER_NCOMBO15 NT_NAMED_INITIALIZER_NCOMBO14, NT_INITIALIZER_LIST_FORWARD(15)
#define NT_NAMED_INITIALIZER_NCOMBO16 NT_NAMED_INITIALIZER_NCOMBO15, NT_INITIALIZER_LIST_FORWARD(16)
#define NT_NAMED_INITIALIZER_NCOMBO17 NT_NAMED_INITIALIZER_NCOMBO16, NT_INITIALIZER_LIST_FORWARD(17)
#define NT_NAMED_INITIALIZER_NCOMBO18 NT_NAMED_INITIALIZER_NCOMBO17, NT_INITIALIZER_LIST_FORWARD(18)
#define NT_NAMED_INITIALIZER_NCOMBO19 NT_NAMED_INITIALIZER_NCOMBO18, NT_INITIALIZER_LIST_FORWARD(19)
#define NT_NAMED_INITIALIZER_NCOMBO20 NT_NAMED_INITIALIZER_NCOMBO19, NT_INITIALIZER_LIST_FORWARD(20)
#define NT_NAMED_INITIALIZER_NCOMBO21 NT_NAMED_INITIALIZER_NCOMBO20, NT_INITIALIZER_LIST_FORWARD(21)
#define NT_NAMED_INITIALIZER_NCOMBO22 NT_NAMED_INITIALIZER_NCOMBO21, NT_INITIALIZER_LIST_FORWARD(22)
#define NT_NAMED_INITIALIZER_NCOMBO23 NT_NAMED_INITIALIZER_NCOMBO22, NT_INITIALIZER_LIST_FORWARD(23)
#define NT_NAMED_INITIALIZER_NCOMBO24 NT_NAMED_INITIALIZER_NCOMBO23, NT_INITIALIZER_LIST_FORWARD(24)
#define NT_NAMED_INITIALIZER_NCOMBO25 NT_NAMED_INITIALIZER_NCOMBO24, NT_INITIALIZER_LIST_FORWARD(25)
#define NT_NAMED_INITIALIZER_NCOMBO26 NT_NAMED_INITIALIZER_NCOMBO25, NT_INITIALIZER_LIST_FORWARD(26)
#define NT_NAMED_INITIALIZER_NCOMBO27 NT_NAMED_INITIALIZER_NCOMBO26, NT_INITIALIZER_LIST_FORWARD(27)
#define NT_NAMED_INITIALIZER_NCOMBO28 NT_NAMED_INITIALIZER_NCOMBO27, NT_INITIALIZER_LIST_FORWARD(28)
#define NT_NAMED_INITIALIZER_NCOMBO29 NT_NAMED_INITIALIZER_NCOMBO28, NT_INITIALIZER_LIST_FORWARD(29)
#define NT_NAMED_INITIALIZER_NCOMBO30 NT_NAMED_INITIALIZER_NCOMBO29, NT_INITIALIZER_LIST_FORWARD(30)
#define NT_NAMED_INITIALIZER_NCOMBO31 NT_NAMED_INITIALIZER_NCOMBO30, NT_INITIALIZER_LIST_FORWARD(31)
#define NT_NAMED_INITIALIZER_NCOMBO32 NT_NAMED_INITIALIZER_NCOMBO31, NT_INITIALIZER_LIST_FORWARD(32)
#define NT_NAMED_INITIALIZER_NCOMBO33 NT_NAMED_INITIALIZER_NCOMBO32, NT_INITIALIZER_LIST_FORWARD(33)
#define NT_NAMED_INITIALIZER_NCOMBO34 NT_NAMED_INITIALIZER_NCOMBO33, NT_INITIALIZER_LIST_FORWARD(34)
#define NT_NAMED_INITIALIZER_NCOMBO35 NT_NAMED_INITIALIZER_NCOMBO34, NT_INITIALIZER_LIST_FORWARD(35)
#define NT_NAMED_INITIALIZER_NCOMBO36 NT_NAMED_INITIALIZER_NCOMBO35, NT_INITIALIZER_LIST_FORWARD(36)
#define NT_NAMED_INITIALIZER_NCOMBO37 NT_NAMED_INITIALIZER_NCOMBO36, NT_INITIALIZER_LIST_FORWARD(37)
#define NT_NAMED_INITIALIZER_NCOMBO38 NT_NAMED_INITIALIZER_NCOMBO37, NT_INITIALIZER_LIST_FORWARD(38)
#define NT_NAMED_INITIALIZER_NCOMBO39 NT_NAMED_INITIALIZER_NCOMBO38, NT_INITIALIZER_LIST_FORWARD(39)
#define NT_NAMED_INITIALIZER_NCOMBO40 NT_NAMED_INITIALIZER_NCOMBO39, NT_INITIALIZER_LIST_FORWARD(40)
#define NT_NAMED_INITIALIZER_NCOMBO41 NT_NAMED_INITIALIZER_NCOMBO40, NT_INITIALIZER_LIST_FORWARD(41)
#define NT_NAMED_INITIALIZER_NCOMBO42 NT_NAMED_INITIALIZER_NCOMBO41, NT_INITIALIZER_LIST_FORWARD(42)
#define NT_NAMED_INITIALIZER_NCOMBO43 NT_NAMED_INITIALIZER_NCOMBO42, NT_INITIALIZER_LIST_FORWARD(43)
#define NT_NAMED_INITIALIZER_NCOMBO44 NT_NAMED_INITIALIZER_NCOMBO43, NT_INITIALIZER_LIST_FORWARD(44)
#define NT_NAMED_INITIALIZER_NCOMBO45 NT_NAMED_INITIALIZER_NCOMBO44, NT_INITIALIZER_LIST_FORWARD(45)
#define NT_NAMED_INITIALIZER_NCOMBO46 NT_NAMED_INITIALIZER_NCOMBO45, NT_INITIALIZER_LIST_FORWARD(46)
#define NT_NAMED_INITIALIZER_NCOMBO47 NT_NAMED_INITIALIZER_NCOMBO46, NT_INITIALIZER_LIST_FORWARD(47)
#define NT_NAMED_INITIALIZER_NCOMBO48 NT_NAMED_INITIALIZER_NCOMBO47, NT_INITIALIZER_LIST_FORWARD(48)
#define NT_NAMED_INITIALIZER_NCOMBO49 NT_NAMED_INITIALIZER_NCOMBO48, NT_INITIALIZER_LIST_FORWARD(49)
#define NT_NAMED_INITIALIZER_NCOMBO50 NT_NAMED_INITIALIZER_NCOMBO49, NT_INITIALIZER_LIST_FORWARD(50)
#define NT_NAMED_INITIALIZER_NCOMBO51 NT_NAMED_INITIALIZER_NCOMBO50, NT_INITIALIZER_LIST_FORWARD(51)
#define NT_NAMED_INITIALIZER_NCOMBO52 NT_NAMED_INITIALIZER_NCOMBO51, NT_INITIALIZER_LIST_FORWARD(52)
#define NT_NAMED_INITIALIZER_NCOMBO53 NT_NAMED_INITIALIZER_NCOMBO52, NT_INITIALIZER_LIST_FORWARD(53)
#define NT_NAMED_INITIALIZER_NCOMBO54 NT_NAMED_INITIALIZER_NCOMBO53, NT_INITIALIZER_LIST_FORWARD(54)
#define NT_NAMED_INITIALIZER_NCOMBO55 NT_NAMED_INITIALIZER_NCOMBO54, NT_INITIALIZER_LIST_FORWARD(55)
#define NT_NAMED_INITIALIZER_NCOMBO56 NT_NAMED_INITIALIZER_NCOMBO55, NT_INITIALIZER_LIST_FORWARD(56)
#define NT_NAMED_INITIALIZER_NCOMBO57 NT_NAMED_INITIALIZER_NCOMBO56, NT_INITIALIZER_LIST_FORWARD(57)
#define NT_NAMED_INITIALIZER_NCOMBO58 NT_NAMED_INITIALIZER_NCOMBO57, NT_INITIALIZER_LIST_FORWARD(58)
#define NT_NAMED_INITIALIZER_NCOMBO59 NT_NAMED_INITIALIZER_NCOMBO58, NT_INITIALIZER_LIST_FORWARD(59)
#define NT_NAMED_INITIALIZER_NCOMBO60 NT_NAMED_INITIALIZER_NCOMBO59, NT_INITIALIZER_LIST_FORWARD(60)
#define NT_NAMED_INITIALIZER_NCOMBO61 NT_NAMED_INITIALIZER_NCOMBO60, NT_INITIALIZER_LIST_FORWARD(61)
#define NT_NAMED_INITIALIZER_NCOMBO62 NT_NAMED_INITIALIZER_NCOMBO61, NT_INITIALIZER_LIST_FORWARD(62)
#define NT_NAMED_INITIALIZER_NCOMBO63 NT_NAMED_INITIALIZER_NCOMBO62, NT_INITIALIZER_LIST_FORWARD(63)
#define NT_NAMED_INITIALIZER_NCOMBO64 NT_NAMED_INITIALIZER_NCOMBO63, NT_INITIALIZER_LIST_FORWARD(64)
#define NT_NAMED_INITIALIZER_NCOMBO65 NT_NAMED_INITIALIZER_NCOMBO64, NT_INITIALIZER_LIST_FORWARD(65)
#define NT_NAMED_INITIALIZER_NCOMBO66 NT_NAMED_INITIALIZER_NCOMBO65, NT_INITIALIZER_LIST_FORWARD(66)
#define NT_NAMED_INITIALIZER_NCOMBO67 NT_NAMED_INITIALIZER_NCOMBO66, NT_INITIALIZER_LIST_FORWARD(67)
#define NT_NAMED_INITIALIZER_NCOMBO68 NT_NAMED_INITIALIZER_NCOMBO67, NT_INITIALIZER_LIST_FORWARD(68)
#define NT_NAMED_INITIALIZER_NCOMBO69 NT_NAMED_INITIALIZER_NCOMBO68, NT_INITIALIZER_LIST_FORWARD(69)
#define NT_NAMED_INITIALIZER_NCOMBO70 NT_NAMED_INITIALIZER_NCOMBO69, NT_INITIALIZER_LIST_FORWARD(70)
#define NT_NAMED_INITIALIZER_NCOMBO71 NT_NAMED_INITIALIZER_NCOMBO70, NT_INITIALIZER_LIST_FORWARD(71)
#define NT_NAMED_INITIALIZER_NCOMBO72 NT_NAMED_INITIALIZER_NCOMBO71, NT_INITIALIZER_LIST_FORWARD(72)
#define NT_NAMED_INITIALIZER_NCOMBO73 NT_NAMED_INITIALIZER_NCOMBO72, NT_INITIALIZER_LIST_FORWARD(73)
#define NT_NAMED_INITIALIZER_NCOMBO74 NT_NAMED_INITIALIZER_NCOMBO73, NT_INITIALIZER_LIST_FORWARD(74)
#define NT_NAMED_INITIALIZER_NCOMBO75 NT_NAMED_INITIALIZER_NCOMBO74, NT_INITIALIZER_LIST_FORWARD(75)
#define NT_NAMED_INITIALIZER_NCOMBO76 NT_NAMED_INITIALIZER_NCOMBO75, NT_INITIALIZER_LIST_FORWARD(76)
#define NT_NAMED_INITIALIZER_NCOMBO77 NT_NAMED_INITIALIZER_NCOMBO76, NT_INITIALIZER_LIST_FORWARD(77)
#define NT_NAMED_INITIALIZER_NCOMBO78 NT_NAMED_INITIALIZER_NCOMBO77, NT_INITIALIZER_LIST_FORWARD(78)
#define NT_NAMED_INITIALIZER_NCOMBO79 NT_NAMED_INITIALIZER_NCOMBO78, NT_INITIALIZER_LIST_FORWARD(79)
#define NT_NAMED_INITIALIZER_NCOMBO80 NT_NAMED_INITIALIZER_NCOMBO79, NT_INITIALIZER_LIST_FORWARD(80)
#define NT_NAMED_INITIALIZER_NCOMBO81 NT_NAMED_INITIALIZER_NCOMBO80, NT_INITIALIZER_LIST_FORWARD(81)
#define NT_NAMED_INITIALIZER_NCOMBO82 NT_NAMED_INITIALIZER_NCOMBO81, NT_INITIALIZER_LIST_FORWARD(82)
#define NT_NAMED_INITIALIZER_NCOMBO83 NT_NAMED_INITIALIZER_NCOMBO82, NT_INITIALIZER_LIST_FORWARD(83)
#define NT_NAMED_INITIALIZER_NCOMBO84 NT_NAMED_INITIALIZER_NCOMBO83, NT_INITIALIZER_LIST_FORWARD(84)
#define NT_NAMED_INITIALIZER_NCOMBO85 NT_NAMED_INITIALIZER_NCOMBO84, NT_INITIALIZER_LIST_FORWARD(85)
#define NT_NAMED_INITIALIZER_NCOMBO86 NT_NAMED_INITIALIZER_NCOMBO85, NT_INITIALIZER_LIST_FORWARD(86)
#define NT_NAMED_INITIALIZER_NCOMBO87 NT_NAMED_INITIALIZER_NCOMBO86, NT_INITIALIZER_LIST_FORWARD(87)
#define NT_NAMED_INITIALIZER_NCOMBO88 NT_NAMED_INITIALIZER_NCOMBO87, NT_INITIALIZER_LIST_FORWARD(88)
#define NT_NAMED_INITIALIZER_NCOMBO89 NT_NAMED_INITIALIZER_NCOMBO88, NT_INITIALIZER_LIST_FORWARD(89)
#define NT_NAMED_INITIALIZER_NCOMBO90 NT_NAMED_INITIALIZER_NCOMBO89, NT_INITIALIZER_LIST_FORWARD(90)
#define NT_NAMED_INITIALIZER_NCOMBO91 NT_NAMED_INITIALIZER_NCOMBO90, NT_INITIALIZER_LIST_FORWARD(91)
#define NT_NAMED_INITIALIZER_NCOMBO92 NT_NAMED_INITIALIZER_NCOMBO91, NT_INITIALIZER_LIST_FORWARD(92)
#define NT_NAMED_INITIALIZER_NCOMBO93 NT_NAMED_INITIALIZER_NCOMBO92, NT_INITIALIZER_LIST_FORWARD(93)
#define NT_NAMED_INITIALIZER_NCOMBO94 NT_NAMED_INITIALIZER_NCOMBO93, NT_INITIALIZER_LIST_FORWARD(94)
#define NT_NAMED_INITIALIZER_NCOMBO95 NT_NAMED_INITIALIZER_NCOMBO94, NT_INITIALIZER_LIST_FORWARD(95)
#define NT_NAMED_INITIALIZER_NCOMBO96 NT_NAMED_INITIALIZER_NCOMBO95, NT_INITIALIZER_LIST_FORWARD(96)
#define NT_NAMED_INITIALIZER_NCOMBO97 NT_NAMED_INITIALIZER_NCOMBO96, NT_INITIALIZER_LIST_FORWARD(97)
#define NT_NAMED_INITIALIZER_NCOMBO98 NT_NAMED_INITIALIZER_NCOMBO97, NT_INITIALIZER_LIST_FORWARD(98)
#define NT_NAMED_INITIALIZER_NCOMBO99 NT_NAMED_INITIALIZER_NCOMBO98, NT_INITIALIZER_LIST_FORWARD(99)
#define NT_NAMED_INITIALIZER_NCOMBO100 NT_NAMED_INITIALIZER_NCOMBO99, NT_INITIALIZER_LIST_FORWARD(100)


#define NT_MAKE_INITIALIZER_LIST_FUNCTION(func_name, func_location, TEMPLATES, ARGS, NAMES)\
template<TEMPLATES>\
inline decltype(auto) func_name(ARGS){return func_location(NAMES);}

#define NT_NAMED_IL_FUNCN(N, f1, f2, ARGS)\
    NT_MAKE_INITIALIZER_LIST_FUNCTION(f1, f2, NT_NAMED_INITIALIZER_TCOMBO##N, NT_EXPAND ARGS, NT_EXPAND( NT_NAMED_INITIALIZER_NCOMBO##N ))



#define NT_MAKE_NAMED_IL_FUNCN(N, f1, f2)\
    NT_NAMED_ARGUMENTS_CONCAT_(NT_NAMED_INITIALIZER_COMBO,N)(NT_NAMED_IL_FUNCN, N, f1, f2, NT_TARG(N))\
    NT_NAMED_ARGUMENTS_CONCAT_(NT_NAMED_INITIALIZER_COMBO,N)(NT_NAMED_IL_FUNCN, N, f1, f2, NT_LARG(N))
        

#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_1(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(1, func_name, func_location)
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_2(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(2, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_1(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_3(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(3, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_2(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_4(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(4, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_3(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_5(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(5, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_4(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_6(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(6, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_5(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_7(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(7, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_6(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_8(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(8, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_7(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_9(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(9, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_8(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_10(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(10, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_9(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_11(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(11, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_10(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_12(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(12, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_11(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_13(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(13, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_12(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_14(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(14, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_13(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_15(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(15, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_14(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_16(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(16, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_15(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_17(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(17, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_16(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_18(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(18, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_17(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_19(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(19, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_18(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_20(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(20, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_19(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_21(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(21, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_20(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_22(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(22, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_21(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_23(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(23, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_22(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_24(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(24, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_23(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_25(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(25, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_24(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_26(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(26, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_25(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_27(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(27, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_26(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_28(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(28, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_27(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_29(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(29, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_28(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_30(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(30, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_29(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_31(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(31, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_30(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_32(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(32, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_31(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_33(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(33, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_32(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_34(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(34, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_33(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_35(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(35, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_34(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_36(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(36, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_35(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_37(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(37, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_36(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_38(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(38, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_37(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_39(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(39, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_38(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_40(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(40, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_39(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_41(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(41, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_40(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_42(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(42, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_41(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_43(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(43, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_42(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_44(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(44, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_43(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_45(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(45, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_44(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_46(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(46, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_45(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_47(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(47, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_46(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_48(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(48, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_47(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_49(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(49, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_48(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_50(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(50, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_49(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_51(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(51, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_50(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_52(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(52, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_51(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_53(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(53, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_52(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_54(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(54, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_53(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_55(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(55, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_54(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_56(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(56, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_55(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_57(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(57, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_56(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_58(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(58, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_57(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_59(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(59, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_58(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_60(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(60, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_59(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_61(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(61, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_60(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_62(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(62, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_61(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_63(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(63, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_62(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_64(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(64, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_63(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_65(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(65, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_64(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_66(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(66, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_65(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_67(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(67, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_66(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_68(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(68, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_67(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_69(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(69, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_68(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_70(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(70, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_69(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_71(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(71, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_70(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_72(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(72, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_71(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_73(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(73, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_72(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_74(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(74, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_73(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_75(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(75, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_74(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_76(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(76, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_75(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_77(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(77, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_76(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_78(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(78, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_77(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_79(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(79, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_78(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_80(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(80, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_79(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_81(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(81, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_80(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_82(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(82, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_81(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_83(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(83, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_82(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_84(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(84, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_83(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_85(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(85, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_84(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_86(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(86, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_85(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_87(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(87, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_86(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_88(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(88, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_87(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_89(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(89, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_88(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_90(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(90, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_89(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_91(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(91, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_90(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_92(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(92, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_91(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_93(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(93, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_92(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_94(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(94, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_93(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_95(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(95, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_94(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_96(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(96, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_95(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_97(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(97, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_96(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_98(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(98, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_97(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_99(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(99, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_98(func_name, func_location) 
#define NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_100(func_name, func_location) NT_MAKE_NAMED_IL_FUNCN(100, func_name, func_location) NT_REFLECT_NAMED_INITIALIZER_LIST_FUNCTION_99(func_name, func_location) 

#endif
